

/* Deleting missing values, column name will be adjusted.*/
DELETE FROM DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
WHERE CROP_TYPE IS NULL OR TRIM(CROP_TYPE) = '';

DELETE FROM DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
WHERE CROP_YIELD IS NULL OR TRIM(CROP_TYPE) = '';

DELETE FROM DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
WHERE GROWTH_STAGE IS NULL OR TRIM(CROP_TYPE) = '';

DELETE FROM DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
WHERE TIMESTAMP IS NULL OR TRIM(TIMESTAMP) = '';

DELETE FROM DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
WHERE PEST_ISSUE IS NULL OR TRIM(PEST_ISSUE) = '';

/* Ensuring data type is accurate */
ALTER TABLE DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
MODIFY COLUMN CROP_YIELD INTEGER;

DELETE FROM DFA23RAWDATA.FBG1200.STAGING_IRRIGATION_DATA
WHERE IRRIGATION_DURATION_MIN IS NULL OR TRIM(IRRIGATION_METHOD) = '';


DELETE FROM DFA23RAWDATA.FBG1200.STAGING_LOCATION_RAW_DATA
WHERE LATITUDE IS NULL OR TRIM(LATITUDE) = '';

-- Convert LATITUDE to FLOAT
ALTER TABLE DFA23RAWDATA.FBG1200.STAGING_LOCATION_RAW_DATA
MODIFY COLUMN LATITUDE FLOAT;

-- Convert LONGITUDE to FLOAT
ALTER TABLE DFA23RAWDATA.FBG1200.STAGING_LOCATION_RAW_DATA
MODIFY COLUMN LONGITUDE FLOAT;

-- Convert ELEVATION to FLOAT
ALTER TABLE DFA23RAWDATA.FBG1200.STAGING_LOCATION_RAW_DATA
MODIFY COLUMN ELEVATION FLOAT;

DELETE FROM DFA23RAWDATA.FBG1200.STAGING_PEST_DATA
WHERE PEST_DESCRIPTION IS NULL OR TRIM(PEST_DESCRIPTION) = '';

UPDATE DFA23RAWDATA.FBG1200.STAGING_PEST_DATA
SET PEST_TYPE = 'Slugs'
WHERE PEST_TYPE = 'Slogs';

DELETE FROM DFA23RAWDATA.FBG1200.STAGING_SENSOR_RAW_DATA
WHERE SOIL_MOISTURE IS NULL;

DELETE FROM DFA23RAWDATA.FBG1200.STAGING_SOIL_RAW_DATA
WHERE NITROGEN_LEVEL IS NULL;

DELETE FROM DFA23RAWDATA.FBG1200.STAGING_WEATHER_RAW_DATA
WHERE WEATHER_CONDITION IS NULL OR TRIM(WEATHER_CONDITION) = '';

select distinct crop_type from DFA23RAWDATA.FBG1200.STAGING_CROP_DATA;

UPDATE DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
SET CROP_TYPE = 'Corn'
WHERE CROP_TYPE = 'Cron';

UPDATE DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
SET CROP_TYPE = 'Wheat'
WHERE CROP_TYPE = 'Wheaat';

select distinct growth_stage from DFA23RAWDATA.FBG1200.STAGING_CROP_DATA;

UPDATE DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
SET growth_stage = 'Vegetative'
WHERE growth_stage = 'Vegatative';

UPDATE DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
SET growth_stage = 'Flowering'
WHERE growth_stage = 'Flowerring';

select distinct pest_issue from DFA23RAWDATA.FBG1200.STAGING_CROP_DATA;

UPDATE DFA23RAWDATA.FBG1200.STAGING_CROP_DATA
SET pest_issue = 'Aphids'
WHERE pest_issue = 'Aphidds';

select distinct irrigation_method from DFA23RAWDATA.FBG1200.STAGING_IRRIGATION_DATA;

UPDATE DFA23RAWDATA.FBG1200.STAGING_IRRIGATION_DATA
SET irrigation_method = 'Drip'
WHERE irrigation_method = 'Driip';

UPDATE DFA23RAWDATA.FBG1200.STAGING_IRRIGATION_DATA
SET irrigation_method = 'Sprinkler'
WHERE irrigation_method = 'Spinkler';

select distinct water_source from DFA23RAWDATA.FBG1200.STAGING_IRRIGATION_DATA;

UPDATE DFA23RAWDATA.FBG1200.STAGING_IRRIGATION_DATA
SET water_source = 'Well'
WHERE water_source = 'Wel';

UPDATE DFA23RAWDATA.FBG1200.STAGING_IRRIGATION_DATA
SET water_source = 'River'
WHERE water_source = 'Rivver';

select distinct pest_type from DFA23RAWDATA.FBG1200.STAGING_PEST_DATA;

UPDATE DFA23RAWDATA.FBG1200.STAGING_PEST_DATA
SET pest_type = 'Aphids'
WHERE pest_type = 'Aphiods';

select distinct pest_severity from DFA23RAWDATA.FBG1200.STAGING_PEST_DATA;

UPDATE DFA23RAWDATA.FBG1200.STAGING_PEST_DATA
SET pest_severity = 'High'
WHERE pest_severity = 'Hihg';

select distinct weather_condition from DFA23RAWDATA.FBG1200.STAGING_WEATHER_RAW_DATA;

UPDATE DFA23RAWDATA.FBG1200.STAGING_WEATHER_RAW_DATA
SET weather_condition = 'Partly Cloudy'
WHERE weather_condition = 'Party Cloudy';

UPDATE DFA23RAWDATA.FBG1200.STAGING_WEATHER_RAW_DATA
SET weather_condition = 'Clear'
WHERE weather_condition = 'Claar';